version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: isd_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: isd_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7296
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
