spring:
  application:
    name: isd_backend

  profiles:
    active: prod

  config:
    import: optional:classpath:/application-${spring.profiles.active}.yml

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: jdbc:postgresql://localhost:5432/isd_backend
    username: postgres
    password: 7296
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.boot.context.config: DEBUG

custom:
  frontend:
    address: ${custom.frontend.address}
    port: ${custom.frontend.port}

  my-app:
    address: ${custom.my-app.address}
    port: ${custom.my-app.port}

  neural-network:
    address: ${custom.neural-network.address}
    port: ${custom.neural-network.port}

  storage:
    directory: ${custom.storage.directory}

  tokens:
    sign-key: ${custom.tokens.sign-key}
